# Generated by Django 5.0.7 on 2024-08-21 18:38

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=core.utils.generate_booking_id, max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
